/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminHandoffRouteImport } from './routes/admin-handoff'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'
import { Route as AdminOrdersRouteImport } from './routes/admin_.orders'
import { Route as AdminSettingsRouteImport } from './routes/admin_.settings'
import { Route as CourierTokenRouteImport } from './routes/courier.$token'
import { Route as PlatformSupportRouteImport } from './routes/platform_.support'
import { Route as AdminSettingsDomainRouteImport } from './routes/admin_.settings_.domain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHandoffRoute = AdminHandoffRouteImport.update({
  id: '/admin-handoff',
  path: '/admin-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin_/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin_/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierTokenRoute = CourierTokenRouteImport.update({
  id: '/courier/$token',
  path: '/courier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/platform_/support',
  path: '/platform/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsDomainRoute = AdminSettingsDomainRouteImport.update({
  id: '/admin_/settings_/domain',
  path: '/admin/settings/domain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-handoff': typeof AdminHandoffRoute
  '/agent': typeof AgentRoute
  '/agreement': typeof AgreementRoute
  '/checkout': typeof CheckoutRoute
  '/forbidden': typeof ForbiddenRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/warehouse': typeof WarehouseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/courier/$token': typeof CourierTokenRoute
  '/platform/support': typeof PlatformSupportRoute
  '/admin/settings/domain': typeof AdminSettingsDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-handoff': typeof AdminHandoffRoute
  '/agent': typeof AgentRoute
  '/agreement': typeof AgreementRoute
  '/checkout': typeof CheckoutRoute
  '/forbidden': typeof ForbiddenRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/warehouse': typeof WarehouseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/courier/$token': typeof CourierTokenRoute
  '/platform/support': typeof PlatformSupportRoute
  '/admin/settings/domain': typeof AdminSettingsDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-handoff': typeof AdminHandoffRoute
  '/agent': typeof AgentRoute
  '/agreement': typeof AgreementRoute
  '/checkout': typeof CheckoutRoute
  '/forbidden': typeof ForbiddenRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/warehouse': typeof WarehouseRoute
  '/admin_/dashboard': typeof AdminDashboardRoute
  '/admin_/orders': typeof AdminOrdersRoute
  '/admin_/settings': typeof AdminSettingsRoute
  '/courier/$token': typeof CourierTokenRoute
  '/platform_/support': typeof PlatformSupportRoute
  '/admin_/settings_/domain': typeof AdminSettingsDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-handoff'
    | '/agent'
    | '/agreement'
    | '/checkout'
    | '/forbidden'
    | '/locked'
    | '/login'
    | '/orders'
    | '/platform'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/warehouse'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/settings'
    | '/courier/$token'
    | '/platform/support'
    | '/admin/settings/domain'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-handoff'
    | '/agent'
    | '/agreement'
    | '/checkout'
    | '/forbidden'
    | '/locked'
    | '/login'
    | '/orders'
    | '/platform'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/warehouse'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/settings'
    | '/courier/$token'
    | '/platform/support'
    | '/admin/settings/domain'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-handoff'
    | '/agent'
    | '/agreement'
    | '/checkout'
    | '/forbidden'
    | '/locked'
    | '/login'
    | '/orders'
    | '/platform'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/warehouse'
    | '/admin_/dashboard'
    | '/admin_/orders'
    | '/admin_/settings'
    | '/courier/$token'
    | '/platform_/support'
    | '/admin_/settings_/domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminHandoffRoute: typeof AdminHandoffRoute
  AgentRoute: typeof AgentRoute
  AgreementRoute: typeof AgreementRoute
  CheckoutRoute: typeof CheckoutRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LockedRoute: typeof LockedRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  WarehouseRoute: typeof WarehouseRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CourierTokenRoute: typeof CourierTokenRoute
  PlatformSupportRoute: typeof PlatformSupportRoute
  AdminSettingsDomainRoute: typeof AdminSettingsDomainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-handoff': {
      id: '/admin-handoff'
      path: '/admin-handoff'
      fullPath: '/admin-handoff'
      preLoaderRoute: typeof AdminHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/orders': {
      id: '/admin_/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings': {
      id: '/admin_/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/$token': {
      id: '/courier/$token'
      path: '/courier/$token'
      fullPath: '/courier/$token'
      preLoaderRoute: typeof CourierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/support': {
      id: '/platform_/support'
      path: '/platform/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof PlatformSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings_/domain': {
      id: '/admin_/settings_/domain'
      path: '/admin/settings/domain'
      fullPath: '/admin/settings/domain'
      preLoaderRoute: typeof AdminSettingsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminHandoffRoute: AdminHandoffRoute,
  AgentRoute: AgentRoute,
  AgreementRoute: AgreementRoute,
  CheckoutRoute: CheckoutRoute,
  ForbiddenRoute: ForbiddenRoute,
  LockedRoute: LockedRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  WarehouseRoute: WarehouseRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CourierTokenRoute: CourierTokenRoute,
  PlatformSupportRoute: PlatformSupportRoute,
  AdminSettingsDomainRoute: AdminSettingsDomainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
