/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminHandoffRouteImport } from './routes/admin-handoff'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as CancelOrderRouteImport } from './routes/cancel-order'
import { Route as CancellationsRouteImport } from './routes/cancellations'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as LockedRouteImport } from './routes/locked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as AdminAnalyticsRouteImport } from './routes/admin_.analytics'
import { Route as AdminCouponsRouteImport } from './routes/admin_.coupons'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'
import { Route as AdminOrdersRouteImport } from './routes/admin_.orders'
import { Route as AdminPagesRouteImport } from './routes/admin_.pages'
import { Route as AdminSettingsRouteImport } from './routes/admin_.settings'
import { Route as CourierTokenRouteImport } from './routes/courier.$token'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as PlatformPlansRouteImport } from './routes/platform_.plans'
import { Route as PlatformSupportRouteImport } from './routes/platform_.support'
import { Route as PlatformUpgradesRouteImport } from './routes/platform_.upgrades'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as PwaIconRouteImport } from './routes/pwa.$icon'
import { Route as AdminInventoryLabelsRouteImport } from './routes/admin_.inventory_.labels'
import { Route as AdminInventorySerialsRouteImport } from './routes/admin_.inventory_.serials'
import { Route as AdminMarketingAbandonedCartsRouteImport } from './routes/admin_.marketing.abandoned-carts'
import { Route as AdminMarketingReviewsRouteImport } from './routes/admin_.marketing.reviews'
import { Route as AdminOrdersNewRouteImport } from './routes/admin_.orders_.new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin_.products.$productId'
import { Route as AdminSettingsDomainRouteImport } from './routes/admin_.settings_.domain'
import { Route as AdminSettingsStaffRouteImport } from './routes/admin_.settings_.staff'
import { Route as ApiAdminAnalyticsRouteImport } from './routes/api.admin.analytics'
import { Route as ApiAdminTriggerAbandonedCartsRouteImport } from './routes/api.admin.trigger-abandoned-carts'
import { Route as CheckoutBitOrderIdRouteImport } from './routes/checkout_.bit.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHandoffRoute = AdminHandoffRouteImport.update({
  id: '/admin-handoff',
  path: '/admin-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelOrderRoute = CancelOrderRouteImport.update({
  id: '/cancel-order',
  path: '/cancel-order',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationsRoute = CancellationsRouteImport.update({
  id: '/cancellations',
  path: '/cancellations',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const LockedRoute = LockedRouteImport.update({
  id: '/locked',
  path: '/locked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin_/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin_/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin_/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin_/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin_/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierTokenRoute = CourierTokenRouteImport.update({
  id: '/courier/$token',
  path: '/courier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformPlansRoute = PlatformPlansRouteImport.update({
  id: '/platform_/plans',
  path: '/platform/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSupportRoute = PlatformSupportRouteImport.update({
  id: '/platform_/support',
  path: '/platform/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUpgradesRoute = PlatformUpgradesRouteImport.update({
  id: '/platform_/upgrades',
  path: '/platform/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PwaIconRoute = PwaIconRouteImport.update({
  id: '/pwa/$icon',
  path: '/pwa/$icon',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryLabelsRoute = AdminInventoryLabelsRouteImport.update({
  id: '/admin_/inventory_/labels',
  path: '/admin/inventory/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventorySerialsRoute = AdminInventorySerialsRouteImport.update({
  id: '/admin_/inventory_/serials',
  path: '/admin/inventory/serials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingAbandonedCartsRoute =
  AdminMarketingAbandonedCartsRouteImport.update({
    id: '/admin_/marketing/abandoned-carts',
    path: '/admin/marketing/abandoned-carts',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMarketingReviewsRoute = AdminMarketingReviewsRouteImport.update({
  id: '/admin_/marketing/reviews',
  path: '/admin/marketing/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/admin_/orders_/new',
  path: '/admin/orders/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/admin_/products/$productId',
  path: '/admin/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsDomainRoute = AdminSettingsDomainRouteImport.update({
  id: '/admin_/settings_/domain',
  path: '/admin/settings/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsStaffRoute = AdminSettingsStaffRouteImport.update({
  id: '/admin_/settings_/staff',
  path: '/admin/settings/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnalyticsRoute = ApiAdminAnalyticsRouteImport.update({
  id: '/api/admin/analytics',
  path: '/api/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTriggerAbandonedCartsRoute =
  ApiAdminTriggerAbandonedCartsRouteImport.update({
    id: '/api/admin/trigger-abandoned-carts',
    path: '/api/admin/trigger-abandoned-carts',
    getParentRoute: () => rootRouteImport,
  } as any)
const CheckoutBitOrderIdRoute = CheckoutBitOrderIdRouteImport.update({
  id: '/checkout_/bit/$orderId',
  path: '/checkout/bit/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-handoff': typeof AdminHandoffRoute
  '/agent': typeof AgentRoute
  '/agreement': typeof AgreementRoute
  '/cancel-order': typeof CancelOrderRoute
  '/cancellations': typeof CancellationsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/warehouse': typeof WarehouseRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/courier/$token': typeof CourierTokenRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/upgrades': typeof PlatformUpgradesRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/pwa/$icon': typeof PwaIconRoute
  '/admin/inventory/labels': typeof AdminInventoryLabelsRoute
  '/admin/inventory/serials': typeof AdminInventorySerialsRoute
  '/admin/marketing/abandoned-carts': typeof AdminMarketingAbandonedCartsRoute
  '/admin/marketing/reviews': typeof AdminMarketingReviewsRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/settings/domain': typeof AdminSettingsDomainRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/trigger-abandoned-carts': typeof ApiAdminTriggerAbandonedCartsRoute
  '/checkout/bit/$orderId': typeof CheckoutBitOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-handoff': typeof AdminHandoffRoute
  '/agent': typeof AgentRoute
  '/agreement': typeof AgreementRoute
  '/cancel-order': typeof CancelOrderRoute
  '/cancellations': typeof CancellationsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/warehouse': typeof WarehouseRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/courier/$token': typeof CourierTokenRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/platform/plans': typeof PlatformPlansRoute
  '/platform/support': typeof PlatformSupportRoute
  '/platform/upgrades': typeof PlatformUpgradesRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/pwa/$icon': typeof PwaIconRoute
  '/admin/inventory/labels': typeof AdminInventoryLabelsRoute
  '/admin/inventory/serials': typeof AdminInventorySerialsRoute
  '/admin/marketing/abandoned-carts': typeof AdminMarketingAbandonedCartsRoute
  '/admin/marketing/reviews': typeof AdminMarketingReviewsRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/settings/domain': typeof AdminSettingsDomainRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/trigger-abandoned-carts': typeof ApiAdminTriggerAbandonedCartsRoute
  '/checkout/bit/$orderId': typeof CheckoutBitOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-handoff': typeof AdminHandoffRoute
  '/agent': typeof AgentRoute
  '/agreement': typeof AgreementRoute
  '/cancel-order': typeof CancelOrderRoute
  '/cancellations': typeof CancellationsRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/forbidden': typeof ForbiddenRoute
  '/locked': typeof LockedRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/warehouse': typeof WarehouseRoute
  '/admin_/analytics': typeof AdminAnalyticsRoute
  '/admin_/coupons': typeof AdminCouponsRoute
  '/admin_/dashboard': typeof AdminDashboardRoute
  '/admin_/orders': typeof AdminOrdersRoute
  '/admin_/pages': typeof AdminPagesRoute
  '/admin_/settings': typeof AdminSettingsRoute
  '/courier/$token': typeof CourierTokenRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/platform_/plans': typeof PlatformPlansRoute
  '/platform_/support': typeof PlatformSupportRoute
  '/platform_/upgrades': typeof PlatformUpgradesRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/pwa/$icon': typeof PwaIconRoute
  '/admin_/inventory_/labels': typeof AdminInventoryLabelsRoute
  '/admin_/inventory_/serials': typeof AdminInventorySerialsRoute
  '/admin_/marketing/abandoned-carts': typeof AdminMarketingAbandonedCartsRoute
  '/admin_/marketing/reviews': typeof AdminMarketingReviewsRoute
  '/admin_/orders_/new': typeof AdminOrdersNewRoute
  '/admin_/products/$productId': typeof AdminProductsProductIdRoute
  '/admin_/settings_/domain': typeof AdminSettingsDomainRoute
  '/admin_/settings_/staff': typeof AdminSettingsStaffRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRoute
  '/api/admin/trigger-abandoned-carts': typeof ApiAdminTriggerAbandonedCartsRoute
  '/checkout_/bit/$orderId': typeof CheckoutBitOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-handoff'
    | '/agent'
    | '/agreement'
    | '/cancel-order'
    | '/cancellations'
    | '/checkout'
    | '/contact'
    | '/forbidden'
    | '/locked'
    | '/login'
    | '/orders'
    | '/platform'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/terms'
    | '/warehouse'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/settings'
    | '/courier/$token'
    | '/pages/$slug'
    | '/platform/plans'
    | '/platform/support'
    | '/platform/upgrades'
    | '/product/$productId'
    | '/pwa/$icon'
    | '/admin/inventory/labels'
    | '/admin/inventory/serials'
    | '/admin/marketing/abandoned-carts'
    | '/admin/marketing/reviews'
    | '/admin/orders/new'
    | '/admin/products/$productId'
    | '/admin/settings/domain'
    | '/admin/settings/staff'
    | '/api/admin/analytics'
    | '/api/admin/trigger-abandoned-carts'
    | '/checkout/bit/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-handoff'
    | '/agent'
    | '/agreement'
    | '/cancel-order'
    | '/cancellations'
    | '/checkout'
    | '/contact'
    | '/forbidden'
    | '/locked'
    | '/login'
    | '/orders'
    | '/platform'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/terms'
    | '/warehouse'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/settings'
    | '/courier/$token'
    | '/pages/$slug'
    | '/platform/plans'
    | '/platform/support'
    | '/platform/upgrades'
    | '/product/$productId'
    | '/pwa/$icon'
    | '/admin/inventory/labels'
    | '/admin/inventory/serials'
    | '/admin/marketing/abandoned-carts'
    | '/admin/marketing/reviews'
    | '/admin/orders/new'
    | '/admin/products/$productId'
    | '/admin/settings/domain'
    | '/admin/settings/staff'
    | '/api/admin/analytics'
    | '/api/admin/trigger-abandoned-carts'
    | '/checkout/bit/$orderId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/admin-handoff'
    | '/agent'
    | '/agreement'
    | '/cancel-order'
    | '/cancellations'
    | '/checkout'
    | '/contact'
    | '/forbidden'
    | '/locked'
    | '/login'
    | '/orders'
    | '/platform'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/terms'
    | '/warehouse'
    | '/admin_/analytics'
    | '/admin_/coupons'
    | '/admin_/dashboard'
    | '/admin_/orders'
    | '/admin_/pages'
    | '/admin_/settings'
    | '/courier/$token'
    | '/pages/$slug'
    | '/platform_/plans'
    | '/platform_/support'
    | '/platform_/upgrades'
    | '/product/$productId'
    | '/pwa/$icon'
    | '/admin_/inventory_/labels'
    | '/admin_/inventory_/serials'
    | '/admin_/marketing/abandoned-carts'
    | '/admin_/marketing/reviews'
    | '/admin_/orders_/new'
    | '/admin_/products/$productId'
    | '/admin_/settings_/domain'
    | '/admin_/settings_/staff'
    | '/api/admin/analytics'
    | '/api/admin/trigger-abandoned-carts'
    | '/checkout_/bit/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminHandoffRoute: typeof AdminHandoffRoute
  AgentRoute: typeof AgentRoute
  AgreementRoute: typeof AgreementRoute
  CancelOrderRoute: typeof CancelOrderRoute
  CancellationsRoute: typeof CancellationsRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LockedRoute: typeof LockedRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  WarehouseRoute: typeof WarehouseRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CourierTokenRoute: typeof CourierTokenRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PlatformPlansRoute: typeof PlatformPlansRoute
  PlatformSupportRoute: typeof PlatformSupportRoute
  PlatformUpgradesRoute: typeof PlatformUpgradesRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  PwaIconRoute: typeof PwaIconRoute
  AdminInventoryLabelsRoute: typeof AdminInventoryLabelsRoute
  AdminInventorySerialsRoute: typeof AdminInventorySerialsRoute
  AdminMarketingAbandonedCartsRoute: typeof AdminMarketingAbandonedCartsRoute
  AdminMarketingReviewsRoute: typeof AdminMarketingReviewsRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminSettingsDomainRoute: typeof AdminSettingsDomainRoute
  AdminSettingsStaffRoute: typeof AdminSettingsStaffRoute
  ApiAdminAnalyticsRoute: typeof ApiAdminAnalyticsRoute
  ApiAdminTriggerAbandonedCartsRoute: typeof ApiAdminTriggerAbandonedCartsRoute
  CheckoutBitOrderIdRoute: typeof CheckoutBitOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-handoff': {
      id: '/admin-handoff'
      path: '/admin-handoff'
      fullPath: '/admin-handoff'
      preLoaderRoute: typeof AdminHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel-order': {
      id: '/cancel-order'
      path: '/cancel-order'
      fullPath: '/cancel-order'
      preLoaderRoute: typeof CancelOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellations': {
      id: '/cancellations'
      path: '/cancellations'
      fullPath: '/cancellations'
      preLoaderRoute: typeof CancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locked': {
      id: '/locked'
      path: '/locked'
      fullPath: '/locked'
      preLoaderRoute: typeof LockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/analytics': {
      id: '/admin_/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/coupons': {
      id: '/admin_/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/orders': {
      id: '/admin_/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/pages': {
      id: '/admin_/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings': {
      id: '/admin_/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/$token': {
      id: '/courier/$token'
      path: '/courier/$token'
      fullPath: '/courier/$token'
      preLoaderRoute: typeof CourierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/plans': {
      id: '/platform_/plans'
      path: '/platform/plans'
      fullPath: '/platform/plans'
      preLoaderRoute: typeof PlatformPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/support': {
      id: '/platform_/support'
      path: '/platform/support'
      fullPath: '/platform/support'
      preLoaderRoute: typeof PlatformSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform_/upgrades': {
      id: '/platform_/upgrades'
      path: '/platform/upgrades'
      fullPath: '/platform/upgrades'
      preLoaderRoute: typeof PlatformUpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwa/$icon': {
      id: '/pwa/$icon'
      path: '/pwa/$icon'
      fullPath: '/pwa/$icon'
      preLoaderRoute: typeof PwaIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/inventory_/labels': {
      id: '/admin_/inventory_/labels'
      path: '/admin/inventory/labels'
      fullPath: '/admin/inventory/labels'
      preLoaderRoute: typeof AdminInventoryLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/inventory_/serials': {
      id: '/admin_/inventory_/serials'
      path: '/admin/inventory/serials'
      fullPath: '/admin/inventory/serials'
      preLoaderRoute: typeof AdminInventorySerialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/marketing/abandoned-carts': {
      id: '/admin_/marketing/abandoned-carts'
      path: '/admin/marketing/abandoned-carts'
      fullPath: '/admin/marketing/abandoned-carts'
      preLoaderRoute: typeof AdminMarketingAbandonedCartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/marketing/reviews': {
      id: '/admin_/marketing/reviews'
      path: '/admin/marketing/reviews'
      fullPath: '/admin/marketing/reviews'
      preLoaderRoute: typeof AdminMarketingReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/orders_/new': {
      id: '/admin_/orders_/new'
      path: '/admin/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/products/$productId': {
      id: '/admin_/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings_/domain': {
      id: '/admin_/settings_/domain'
      path: '/admin/settings/domain'
      fullPath: '/admin/settings/domain'
      preLoaderRoute: typeof AdminSettingsDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/settings_/staff': {
      id: '/admin_/settings_/staff'
      path: '/admin/settings/staff'
      fullPath: '/admin/settings/staff'
      preLoaderRoute: typeof AdminSettingsStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/analytics': {
      id: '/api/admin/analytics'
      path: '/api/admin/analytics'
      fullPath: '/api/admin/analytics'
      preLoaderRoute: typeof ApiAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/trigger-abandoned-carts': {
      id: '/api/admin/trigger-abandoned-carts'
      path: '/api/admin/trigger-abandoned-carts'
      fullPath: '/api/admin/trigger-abandoned-carts'
      preLoaderRoute: typeof ApiAdminTriggerAbandonedCartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/bit/$orderId': {
      id: '/checkout_/bit/$orderId'
      path: '/checkout/bit/$orderId'
      fullPath: '/checkout/bit/$orderId'
      preLoaderRoute: typeof CheckoutBitOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminHandoffRoute: AdminHandoffRoute,
  AgentRoute: AgentRoute,
  AgreementRoute: AgreementRoute,
  CancelOrderRoute: CancelOrderRoute,
  CancellationsRoute: CancellationsRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ForbiddenRoute: ForbiddenRoute,
  LockedRoute: LockedRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  WarehouseRoute: WarehouseRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CourierTokenRoute: CourierTokenRoute,
  PagesSlugRoute: PagesSlugRoute,
  PlatformPlansRoute: PlatformPlansRoute,
  PlatformSupportRoute: PlatformSupportRoute,
  PlatformUpgradesRoute: PlatformUpgradesRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  PwaIconRoute: PwaIconRoute,
  AdminInventoryLabelsRoute: AdminInventoryLabelsRoute,
  AdminInventorySerialsRoute: AdminInventorySerialsRoute,
  AdminMarketingAbandonedCartsRoute: AdminMarketingAbandonedCartsRoute,
  AdminMarketingReviewsRoute: AdminMarketingReviewsRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminSettingsDomainRoute: AdminSettingsDomainRoute,
  AdminSettingsStaffRoute: AdminSettingsStaffRoute,
  ApiAdminAnalyticsRoute: ApiAdminAnalyticsRoute,
  ApiAdminTriggerAbandonedCartsRoute: ApiAdminTriggerAbandonedCartsRoute,
  CheckoutBitOrderIdRoute: CheckoutBitOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
